[tools]
rust = "latest"

[settings]
experimental = true

[tasks.install]
run = "cargo install --path . --bin pl --bin polars"
description = "System install the pl/polars CLI"

[tasks."build:release"]
run = "cargo build --release"
description = "Build the pl/polars CLI"

[tasks."build:debug"]
run = "cargo build"
description = "Build the pl/polars CLI"

[tasks.test]
run = "cargo test"
description = "Test the pl/polars CLI"

[tasks.lint]
run = "cargo clippy --all-targets -- -D warnings"
description = "Lint the pl/polars CLI"